name: trunk
on:
  push:
    branches: [main]
jobs:
  release-canary:
    if: needs.checkNpmTokenSet.outputs.isNpmTokenSet == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: prisma-labs/dripip@master
        with:
          npmToken: ${{secrets.NPM_TOKEN}}
          githubToken: ${{secrets.GITHUB_TOKEN}}
